/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PlanBuilderRouteImport } from './routes/plan-builder'
import { Route as PayoutCurveRouteImport } from './routes/payout-curve'
import { Route as GoalSettingRouteImport } from './routes/goal-setting'
import { Route as FairnessRouteImport } from './routes/fairness'
import { Route as DataInputsRouteImport } from './routes/data-inputs'
import { Route as IndexRouteImport } from './routes/index'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanBuilderRoute = PlanBuilderRouteImport.update({
  id: '/plan-builder',
  path: '/plan-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutCurveRoute = PayoutCurveRouteImport.update({
  id: '/payout-curve',
  path: '/payout-curve',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalSettingRoute = GoalSettingRouteImport.update({
  id: '/goal-setting',
  path: '/goal-setting',
  getParentRoute: () => rootRouteImport,
} as any)
const FairnessRoute = FairnessRouteImport.update({
  id: '/fairness',
  path: '/fairness',
  getParentRoute: () => rootRouteImport,
} as any)
const DataInputsRoute = DataInputsRouteImport.update({
  id: '/data-inputs',
  path: '/data-inputs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-inputs': typeof DataInputsRoute
  '/fairness': typeof FairnessRoute
  '/goal-setting': typeof GoalSettingRoute
  '/payout-curve': typeof PayoutCurveRoute
  '/plan-builder': typeof PlanBuilderRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-inputs': typeof DataInputsRoute
  '/fairness': typeof FairnessRoute
  '/goal-setting': typeof GoalSettingRoute
  '/payout-curve': typeof PayoutCurveRoute
  '/plan-builder': typeof PlanBuilderRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-inputs': typeof DataInputsRoute
  '/fairness': typeof FairnessRoute
  '/goal-setting': typeof GoalSettingRoute
  '/payout-curve': typeof PayoutCurveRoute
  '/plan-builder': typeof PlanBuilderRoute
  '/reports': typeof ReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-inputs'
    | '/fairness'
    | '/goal-setting'
    | '/payout-curve'
    | '/plan-builder'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-inputs'
    | '/fairness'
    | '/goal-setting'
    | '/payout-curve'
    | '/plan-builder'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/data-inputs'
    | '/fairness'
    | '/goal-setting'
    | '/payout-curve'
    | '/plan-builder'
    | '/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataInputsRoute: typeof DataInputsRoute
  FairnessRoute: typeof FairnessRoute
  GoalSettingRoute: typeof GoalSettingRoute
  PayoutCurveRoute: typeof PayoutCurveRoute
  PlanBuilderRoute: typeof PlanBuilderRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-builder': {
      id: '/plan-builder'
      path: '/plan-builder'
      fullPath: '/plan-builder'
      preLoaderRoute: typeof PlanBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payout-curve': {
      id: '/payout-curve'
      path: '/payout-curve'
      fullPath: '/payout-curve'
      preLoaderRoute: typeof PayoutCurveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal-setting': {
      id: '/goal-setting'
      path: '/goal-setting'
      fullPath: '/goal-setting'
      preLoaderRoute: typeof GoalSettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairness': {
      id: '/fairness'
      path: '/fairness'
      fullPath: '/fairness'
      preLoaderRoute: typeof FairnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-inputs': {
      id: '/data-inputs'
      path: '/data-inputs'
      fullPath: '/data-inputs'
      preLoaderRoute: typeof DataInputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataInputsRoute: DataInputsRoute,
  FairnessRoute: FairnessRoute,
  GoalSettingRoute: GoalSettingRoute,
  PayoutCurveRoute: PayoutCurveRoute,
  PlanBuilderRoute: PlanBuilderRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
